# 线性代数

1.标量

In [3]:
import torch 

x = torch.tensor(3.0)
y = torch.tensor(2.0)  # tensor格式的标量

In [2]:
x+y, x*y, x/y, x**y 

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

2.向量

In [5]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
x[3]

tensor(3)

张量的长度，维度，形状

In [8]:
print(len(x))
print(x.shape)

y = torch.arange(12).reshape(3,4)
print(y.shape)

4
torch.Size([4])
torch.Size([3, 4])


矩阵

In [12]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)

In [10]:
A.T  #矩阵转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]]) #B是一个对称矩阵
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 张量: 矩阵即二维张量

In [14]:
X = torch.arange(24).reshape(2,3,4)  #图像是一个三维张量
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [20]:
Y = X.clone()
Y+X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

### Hadamard积:按元素相乘(逐个做乘法)

In [21]:
Y*X

tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])

In [23]:
a = 2 
print(X)
print(a+X)
print(a*X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])


### 数据降维

In [24]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [25]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [26]:
A.sum()

tensor(190)

In [28]:
A[1].sum()

tensor(22)

指定沿某个轴求和

In [7]:
A_sum_axis0 = A.sum(axis=0)    # axis = 0 即:按照行求和 
A_sum_axis0, A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [8]:
A.sum(axis=[0,1]) #沿着行和列求和（也即对矩阵所有值进行求和）

tensor(190)

In [15]:
A.mean(), A.sum(), A.numel(), A.sum()/A.numel()

(tensor(9.5000), tensor(190.), 20, tensor(9.5000))

非降维形式的求和

In [18]:
sum_A = A.sum(axis=1, keepdims=True)  # 保留了行数：可以通过广播与A做运算
sum_A, A

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [20]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

沿某行/列的顺序计算累计的总和

In [21]:
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]))

### 点积

In [23]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype = torch.float32)
x, y, torch.dot(x,y)
#即x^T·y

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [25]:
#也即x*y求和
torch.sum(x*y), (x*y).sum()

(tensor(6.), tensor(6.))

### 矩阵-向量积

In [26]:
A.shape, x.shape, torch.mv(A,x) #矩阵·向量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

### 矩阵-矩阵积

In [27]:
B = torch.ones(4,3)
torch.mm(A,B) #矩阵乘法，不同于Hadamard积

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 范数

In [28]:
# L2范数
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [29]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [30]:
torch.norm(torch.ones(4,9))
#即根号36

tensor(6.)

## 练习:

In [32]:
#Q1
A = torch.arange(12, dtype=torch.float32).reshape(1,3,4)
(A.T).T == A

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])

In [36]:
#Q2
B = A
B = B+1
A.T+B.T == (A+B).T

tensor([[[True],
         [True],
         [True]],

        [[True],
         [True],
         [True]],

        [[True],
         [True],
         [True]],

        [[True],
         [True],
         [True]]])

In [45]:
x = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
len(x)

2

In [40]:
A/A.sum(axis=1)

tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]]])

In [46]:
x, x.sum(axis=0), x.sum(axis=1), x.sum(axis=2)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [49]:
torch.linalg.norm(x)

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long