# Data Processing --预备知识

In [2]:
import torch 
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [6]:
print(x.size())
print(x.numel())  #numel函数输出元素的总个数

torch.Size([12])
12


In [10]:
x.reshape(3,4)  #优先排列行，再是列
y = x.reshape(-1,4) #希望张量有四列，但是不清楚总共有多少个数
y  #当然也可以用numel来做

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2,3,4)) #两层括号

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

生成标准高斯分布:均值为0，标准差为1

In [13]:
torch.randn(3,4)

tensor([[-1.2823, -1.9054,  1.0786,  0.0183],
        [-0.3209, -0.4304,  2.4318,  0.6853],
        [-0.1476,  0.6301,  1.5869, -1.0403]])

In [19]:
tmp = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tmp[1]

tensor([1, 2, 3, 4])

按<u>元素</u>作张量运算

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])    #加的操作要求满足矩阵特性(行列)
print("x+y = ",(x+y))
print("x*y = ",(x*y)) #这个是做逐项相乘
print("x/y = ",(x/y)) #逐项相除
print("x**y=",(x**y)) #逐项次方
print("e^x=",torch.exp(x)) #把x的每一位作为指数

x+y =  tensor([ 3.,  4.,  6., 10.])
x*y =  tensor([ 2.,  4.,  8., 16.])
x/y =  tensor([0.5000, 1.0000, 2.0000, 4.0000])
x**y= tensor([ 1.,  4., 16., 64.])
e^x= tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


#### 按<u>元素</u>作张量运算

dim = 0 : 在行上叠加

dim = 1 : 在列上叠加

In [34]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
#把x叠加到y上面去

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [37]:
print(X==Y) #返回两个张量各个位置处值对比的结果
print(X>Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [43]:
X.sum() #得到的是一个单元素张量

tensor(66.)

广播机制:在大部分情况下，沿着长度为1的轴进行广播。
机制为:先复制再相加

In [45]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a,b)
print("a+b=",a+b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
a+b= tensor([[0, 1],
        [1, 2],
        [2, 3]])


当广播长度不为1时出现报错

### 索引和切片

In [65]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(X[-1])  #输出的是最后一行
print(X[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


写入

In [52]:
X[1,2] = 9 
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [58]:
X[0:3]  #A:B表示第A行到第B-1行
X[0:2,:] = 12 #为选出的行赋值
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 节省内存

In [59]:
#通过id()函数可以查看数据存放位置
before = id(Y)
Y = Y+X
id(Y) == before
#发现Y被指向了一个新的地址

False

执行原地操作的方法:

In [60]:
 #1
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X+Y
print(id(Z))

2046757238400
2046757238400


In [66]:
print(id(X))
X += Y     #用+=操作也可行
print(id(X))

2046757237600
2046757237600


#### 转换为其它python对象

也即：将张量和其它库的python对象进行互相转换

In [67]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [68]:
A,B

(array([[14., 14., 18., 18.],
        [17., 19., 21., 23.],
        [20., 21., 22., 23.]], dtype=float32),
 tensor([[14., 14., 18., 18.],
         [17., 19., 21., 23.],
         [20., 21., 22., 23.]]))

将张量转化为标量

In [81]:
a = torch.tensor([3.1,2.5])
for i in range(len(a)):
    a[i] = int(a[i])
a

tensor([3., 2.])

In [84]:
a = a.int()

In [85]:
a = a.float()
a

tensor([3., 2.])

以上的方法可以快速转换torch内数据的形式

练习T2

In [111]:
#替换张量:
a = torch.arange(4).reshape(1,2,2)
b = torch.arange(8).reshape(4,1,2)
a,b   #需要保证

(tensor([[[0, 1],
          [2, 3]]]),
 tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]],
 
         [[6, 7]]]))

In [112]:
a+b

tensor([[[ 0,  2],
         [ 2,  4]],

        [[ 2,  4],
         [ 4,  6]],

        [[ 4,  6],
         [ 6,  8]],

        [[ 6,  8],
         [ 8, 10]]])